apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "anuj.ga01@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "ukkd dreh qjek jolz"
type: Opaque